### ISSUE TITLE
Error in using lr_find( ) for BioBert NER

### ISSUE THREAD

**Issue by miladnouriezade** [amaiya/ktrain#106]
Hi, I'm trying to use `lr_find()` function for BioBert NER using this code

```bash
import ktrain
from ktrain import text
# Load data
(trn, val, preproc) = text.entities_from_txt('./datasets/BC5CDR-IOB/train.tsv',val_filepath='./datasets/BC5CDR-IOB/devel.tsv', data_format='conll2003')
# Load model
model = text.sequence_tagger('bilstm-bert', preproc, bert_model='monologg/biobert_v1.1_pubmed')
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=32, eval_batch_size=8)
learner.lr_find(show_plot=True, max_epochs=1)
```
but I got the following error
```bash
Traceback (most recent call last):
  File "/Users/miladnourizade/Documents/Ktrain/main.py", line 11, in <module>
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/ktrain/core.py", line 468, in lr_find
    verbose=verbose)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/ktrain/lroptimize/lrfinder.py", line 117, in find
    callbacks=[callback])
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 606, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 613, in __init__
    output_shapes=nested_shape)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 540, in from_generator
    output_types, tensor_shape.as_shape, output_shapes)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py", line 471, in map_structure_up_to
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py", line 471, in <listcomp>
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1216, in as_shape
    return TensorShape(shape)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/Users/miladnourizade/anaconda3/envs/Ktrain/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 193, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

**Comment by miladnouriezade** [comment]
It was TensorFlow problem, I changed `TensorFlow 2.00` to `TensorFlow 2.1.0` and it works.
