### ISSUE TITLE
SyntaxError when importing ktrain

### ISSUE THREAD

**Issue by daviduarte** [amaiya/ktrain#11]
Python version: 3.5
OS: Linux 16.04
Instalation by: pip3

When I put: 
`import ktrain`

raise the error:

```
Traceback (most recent call last):
  File "bert.py", line 9, in <module>
    import ktrain
  File "/usr/local/lib/python3.5/dist-packages/ktrain/__init__.py", line 2, in <module>
    from .core import *
  File "/usr/local/lib/python3.5/dist-packages/ktrain/core.py", line 1, in <module>
    from .imports import *
  File "/usr/local/lib/python3.5/dist-packages/ktrain/imports.py", line 30, in <module>
    from fastprogress import master_bar, progress_bar 
  File "/usr/local/lib/python3.5/dist-packages/fastprogress/__init__.py", line 1, in <module>
    from .fastprogress import master_bar, progress_bar, force_console_behavior
  File "/usr/local/lib/python3.5/dist-packages/fastprogress/fastprogress.py", line 42
    if h!= 0: return f'{h}:{m:02d}:{s:02d}'
                                          ^
SyntaxError: invalid syntax
```

**Comment by amaiya** [comment]
Are you sure you're using Python3?  That error looks like a complaint about Python3 syntax in fastprogress dependency.

**Comment by amaiya** [comment]
It looks like you're using Python3.5.  The fastprogress module (along with ktrain) requires Python3.6 or above.

**Comment by nagarajansriram** [comment]
i got an error 
ValueError: A valid TextPreprocessor object is required for bert/bigru

while running learner=......

please help.

**Comment by amaiya** [comment]
@nagarajansriram `preproc` is a required argument to `text_classifier` if selecting bert or bigru.  IT will be always required in future versions.  

In the future, please post more details including a minimal reproducible example of the problem if you have further issues. Thanks.
