### ISSUE TITLE
Error in importing ktrain

### ISSUE THREAD

**Issue by smritisingh26** [amaiya/ktrain#119]
On importing ktrain, I get an error which says invalid syntax. 
Here's the error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-ccbda6fc29a3>", line 1, in <module>
    import ktrain

  File "/home/smriti/.local/lib/python3.5/site-packages/ktrain/__init__.py", line 2, in <module>
    from .core import *

  File "/home/smriti/.local/lib/python3.5/site-packages/ktrain/core.py", line 1, in <module>
    from .imports import *

  File "/home/smriti/.local/lib/python3.5/site-packages/ktrain/imports.py", line 30, in <module>
    from fastprogress import master_bar, progress_bar

  File "/home/smriti/.local/lib/python3.5/site-packages/fastprogress/__init__.py", line 1, in <module>
    from .fastprogress import master_bar, progress_bar, force_console_behavior, workaround_empty_console_output

  File "/home/smriti/.local/lib/python3.5/site-packages/fastprogress/fastprogress.py", line 46
    if h!= 0: return f'{h}:{m:02d}:{s:02d}'
                                          ^
SyntaxError: invalid syntax

Any help will be much appreciated.

**Comment by amaiya** [comment]
Hello:  You are using Python 3.5.  The fastprogress library used by ktrain (and ktrain itself) require at least Python 3.6.  

If you upgrade to Python 3.6.x, it should work.
