### ISSUE TITLE
Model is Running in Jupyter Notebook but not in Python Script

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#179]
Hi,
Thanks for answering my other questions. I have run into another problem
My code is working in Jupyter Notebook but not in python script.
```
import ktrain
predictor = ktrain.load_predictor('distilbert')
data = ['this movie is really great. deserve lots of praise']
predictor.predict(data)
```
Running fine in a jupyter notebook but throwing this error in a .py file.

```
Traceback (most recent call last):                                                                                                                                                                                   File "app.py", line 6, in <module>                                                                                                                                                                                   predictor = ktrain.load_predictor('distilbert')                                                                                                                                                                  File "C:\ProgramData\Anaconda3\lib\site-packages\ktrain\core.py", line 1341, in load_predictor                                                                                                                       model = _load_model(fpath, preproc=preproc)                                                                                                                                                                      File "C:\ProgramData\Anaconda3\lib\site-packages\ktrain\core.py", line 1404, in _load_model                                                                                                                          model = preproc.get_model(fpath=fpath)                                                                                                                                                                           File "C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py", line 987, in get_model                                                                                                                return self.get_classifier(fpath=fpath)                                                                                                                                                                          File "C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py", line 950, in get_classifier                                                                                                           model = self._load_pretrained(mname, num_labels)                                                                                                                                                                 File "C:\ProgramData\Anaconda3\lib\site-packages\ktrain\text\preprocessor.py", line 917, in _load_pretrained                                                                                                         model = self.model_type.from_pretrained(mname, num_labels=num_labels)                                                                                                                                            File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_utils.py", line 395, in from_pretrained                                                                                                    model(model.dummy_inputs, training=False)  # build the network with dummy inputs                                                                                                                                 File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_distilbert.py", line 712, in call                                                                                                          distilbert_output = self.distilbert(inputs, **kwargs)                                                                                                                                                            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_distilbert.py", line 459, in call                                                                                                          tfmr_output = self.transformer([embedding_output, attention_mask, head_mask], training=training)                                                                                                                 File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_distilbert.py", line 380, in call                                                                                                          layer_outputs = layer_module([hidden_state, attn_mask, head_mask[i]], training=training)                                                                                                                         File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_distilbert.py", line 323, in call                                                                                                          sa_output = self.attention([x, x, x, attn_mask, head_mask], training=training)                                                                                                                                   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_tf_distilbert.py", line 235, in call                                                                                                          q = shape(self.q_lin(query))  # (bs, n_heads, q_length, dim_per_head)                                                                                                                                            File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__                                                                                           outputs = self.call(cast_inputs, *args, **kwargs)                                                                                                                                                                File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 1131, in call                                                                                                    outputs = standard_ops.tensordot(inputs, self.kernel, [[rank - 1], [0]])                                                                                                                                         File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 4106, in tensordot                                                                                                    ab_matmul = matmul(a_reshape, b_reshape)                                                                                                                                                                         File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper                                                                                                      return target(*args, **kwargs)                                                                                                                                                                                   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 2798, in matmul                                                                                                       a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)                                                                                                                                               File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 5616, in mat_mul                                                                                                  _ops.raise_from_not_ok_status(e, name)                                                                                                                                                                           File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6606, in raise_from_not_ok_status                                                                                    six.raise_from(core._status_to_exception(e.code, message), None)                                                                                                                                                 File "<string>", line 3, in raise_from                                                                                                                                                                           tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(15, 768), b.shape=(768, 768), m=15, n=768, k=768 [Op:MatMul] name: tf_distil_bert_for_sequence_classification/distilbert/transformer/layer_._0/attention/q_lin/Tensordot/MatMul/     
```

Any idea why it is happening. I am using Anaconda 3 on Windows 10 Machine.

**Comment by amaiya** [comment]
It looks like the same error you posted in the [other issue](https://github.com/amaiya/ktrain/issues/175#issuecomment-645997662) (`Blas GEMM failed`), which suggests it is either a TensorFlow issue or a memory issue.  Please try the solutions I posted in the other thread.

**Comment by amaiya** [comment]
You should also make sure you shutdown your notebooks before running the `.py` script if memory is limited.

**Comment by laxmimerit** [comment]
Hi Amaiya,
Thanks a lot for being so quick.
You are right. It is memory and resource error. This is happening because of GPU. For testing purpose I had added this line of code at the top to avoid this error.

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Force TF to use only the CPU
```
Now it is running like a charm. Thanks for making such a easy wrapper.
