### ISSUE TITLE
validate method for classification produces out of bounds error

### ISSUE THREAD

**Issue by peterbayerle** [amaiya/ktrain#195]
My code:

```
x_train = ["doc1", ...]
y_train = [1, ...]
class_names = ["action", "comedy"]

t = text.Transformer(MODEL_NAME, maxlen=MAX_LEN, class_names=class_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = get_learner(model, train_data=trn, val_data=val, batch_size=6)

learner.fit_onecycle(8e-5, 1)

learner.validate(class_names=t.get_classes())
```

The error:
```
Traceback (most recent call last):
  File "ktrain_test.py", line 35, in <module>
    learner.validate(class_names=t.get_classes())
  File "/Users/user/Developer/bert/venv/lib/python3.7/site-packages/ktrain/core.py", line 120, in validate
    y_true = np.argmax(y_true, axis=1)
  File "<__array_function__ internals>", line 6, in argmax
  File "/Users/user/Developer/bert/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Users/user/Developer/bert/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

**Comment by amaiya** [comment]
As you can see from [Colab notebook](https://colab.research.google.com/drive/1GZmo89CS7sl7xhyxoyuoEpvq0BRjp1gn?usp=sharing), everything works as expected.

**Are you sure the `val` you're supplying to `get_learner` is the output of `preprocess_test`?  What does `y_test`  look like (i.e., the input to `preprocess_test`)?**

With two classes, running `learner.ground_truth(val_data=val)` should return something that looks like this:
```python
array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)
```
