### ISSUE TITLE
load predictor issue

### ISSUE THREAD

**Issue by emanueledirosa** [amaiya/ktrain#21]
Hi Amaiya,

I saved the predictor with predictor.save in colab, then I ran ktrain.load_predictor in my computer to load the predictor and I get the following error:

Call to keras.models.load_model failed.  Try using the learner.model.save_weights and learner.model.load_weights instead.
Error was:
Traceback (most recent call last):
  File "Bert_Classifier_WS.py", line 16, in <module>
    predictor = ktrain.load_predictor(root_path + 'pred_bert_26.h5')
  File "C:\Users\a2c-admin\AppData\Roaming\Python\Python37\site-packages\ktrain\core.py", line 1199, in load_predictor
    raise ValueError('model must be of instance Model')
ValueError: model must be of instance Model

I pasted  in my computer the 2 files that I obtained by predictor.save in colab.
Any ideas about why I get this error?

Thank you in advance.
Emanuele

**Comment by njofce** [comment]
@emanueledirosa Make sure you have TensorFlow 1.14. I had the same problem with different version of TensorFlow

**Comment by emanueledirosa** [comment]
@njofce thanks this solved the issue about the loading of the predictor. But it shows another issue now while making the prediction.
Any ideas? The same code works well on colab.

  pred = predictor.predict([query])
  File "/home/xxxxx/.local/lib/python3.6/site-packages/ktrain/text/predictor.py", line 48, in predict
    preds = self.model.predict(texts)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1164, in predict
    self._make_predict_function()
  File "/home/xxxxx/.local/lib/python3.6/site-packages/keras/engine/training.py", line 554, in _make_predict_function
    **kwargs)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2744, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2546, in __init__
    with tf.control_dependencies(self.outputs):
  File "/home/xxxxx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5426, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4867, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3875, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense_1/Softmax:0", shape=(?, 698), dtype=float32) is not an element of this graph.

**Comment by njofce** [comment]
@emanueledirosa after loading the predictor, call predictor.model._make_predict_function()
