### ISSUE TITLE
error with text.transformer- roberta-base

### ISSUE THREAD

**Issue by Liranbz** [amaiya/ktrain#310]
Hi, 
I try to train a model based on "roberta-base". I try to run it on EC2 (p3.16xl) , and I got this error:

```
Traceback (most recent call last):
  File "ktrain_transformer_training.py", line 119, in <module>
    learner, preproc = train_transformer(x_train, y_train, x_test, y_test)
  File "ktrain_transformer_training.py", line 98, in train_transformer
    model = t.get_classifier()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 1041, in get_classifier
    model = self._load_pretrained(mname, num_labels)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 1006, in _load_pretrained
    raise ValueError('could not load pretrained model %s using both from_pt=False and from_pt=True' % (mname))
ValueError: could not load pretrained model roberta-base using both from_pt=False and from_pt=True
```
However, the same code runs prefect on my local machine.
can you help with this issue?
Thanks

**Comment by amaiya** [comment]
What happens when you do this on EC2?
```python
from transformers import *
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base')
```

**Comment by Liranbz** [comment]
I got this error:
```
    t = text.Transformer(model, maxlen=args.maxlen)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 1147, in __init__
    maxlen, max_features=10000, class_names=class_names, multilabel=multilabel)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 827, in __init__
    self.name = model_name.split('-')[0]
AttributeError: 'TFRobertaForSequenceClassification' object has no attribute 'split'
```

**Comment by amaiya** [comment]
The argument to `Transformer` must be a model name (e.g., `roberta-base`) or a path to a model. It looks you're feeding an actual model.

**Comment by Liranbz** [comment]
I feed the "model" as you wrote me..

**Comment by amaiya** [comment]
OK - I meant to just try to see if you could load the model to shed more light on what the problem is.

Are there any errors when you do this?
```python
from transformers import *
config = AutoConfig.from_pretrained('roberta-base')
config.num_labels = 4
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)
```

Also, what version of `transformers` and `tensorflow` are installed on EC2?

**Comment by amaiya** [comment]
Can you please clarify what's working and what's not working for you right now?    Are you saying this works?

```python
t = Transformer('roberta=base')
from transformers import *
config = AutoConfig.from_pretrained('roberta-base')
config.num_labels = 4
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)
```
and the code below does NOT work?
```python
t = text.Transformer('roberta-base', maxlen=500, class_names=class_names)
```

**Comment by Liranbz** [comment]
exactly

**Comment by amaiya** [comment]
OK - p[ease share your script.  Thanks.

**Comment by Liranbz** [comment]
Here is my script:

```
import pandas as pd
import ktrain
from ktrain import text
import argparse
from sklearn.model_selection import train_test_split
import os
import pickle
import tensorflow as tf
from transformers import *

config = AutoConfig.from_pretrained('roberta-base')
config.num_labels = 4
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)

t = text.Transformer('roberta-base', maxlen=args.maxlen)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=args.batch_size)
learner.fit_onecycle(lr=args.lr, epochs=args.epochs, checkpoint_folder=args.saved_models_folder)
```

I try to understand why this script works well on my local machine (without gpu) but I got an error once I moved it to EC2
The solution was:
```
from transformers import *
config = AutoConfig.from_pretrained('roberta-base')
config.num_labels = 4
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)
```

**Comment by amaiya** [comment]
What does your  `x_train` and `y_train` look like?  For instance, what do first 5 rows look like?

**Comment by Liranbz** [comment]
x_train=each row data is a string of text
y_train= each row data is a label (defined as category)
before using the t text. transformer I passed the data as a list:

```
x_train, x_test = list(x_train), list(x_test)
y_train, y_test = list(y_train), list(y_test)
```

**Comment by amaiya** [comment]
That information doesn't help in reproducing your problem. Please provide more details.  I need to know the actual format of the labels (e.g., integers, strings, 1-hot-encoded , etc.).

**Comment by amaiya** [comment]
And, how many classes are there?

**Comment by Liranbz** [comment]
sorry about that. its integers, about 3000 classes

**Comment by amaiya** [comment]
Does this produce an error on EC2 for you?

```python
from transformers import *
config = AutoConfig.from_pretrained('roberta-base')
config.num_labels = 3000
model = TFAutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)
```
