### ISSUE TITLE
Invalid default config loading from transformers for Albert, Camembert, XMLroberta

### ISSUE THREAD

**Issue by dtuggener** [amaiya/ktrain#83]
Having some issues with loading ktrain using transformer version 2.1.1
```
Python 3.7.6 (default, Dec 19 2019, 23:49:42) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ktrain
using Keras version: 2.2.4-tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/don/.local/lib/python3.7/site-packages/ktrain/__init__.py", line 3, in <module>
    from .core import ArrayLearner, GenLearner, get_predictor, load_predictor, release_gpu_memory
  File "/home/don/.local/lib/python3.7/site-packages/ktrain/core.py", line 10, in <module>
    from .text.preprocessor import TextPreprocessor, BERTPreprocessor, TransformersPreprocessor
  File "/home/don/.local/lib/python3.7/site-packages/ktrain/text/__init__.py", line 1, in <module>
    from .models import *
  File "/home/don/.local/lib/python3.7/site-packages/ktrain/text/models.py", line 3, in <module>
    from . import preprocessor as tpp
  File "/home/don/.local/lib/python3.7/site-packages/ktrain/text/preprocessor.py", line 15, in <module>
    from transformers import AlbertConfig, TFAlbertForSequenceClassification, AlbertTokenizer
ImportError: cannot import name 'AlbertConfig' from 'transformers' (/home/don/.local/lib/python3.7/site-packages/transformers/__init__.py)
```
when comment out the imports in preprocessor.py, it works:
```
from transformers import BertConfig, TFBertForSequenceClassification, BertTokenizer
from transformers import XLNetConfig, TFXLNetForSequenceClassification, XLNetTokenizer
from transformers import XLMConfig, TFXLMForSequenceClassification, XLMTokenizer
from transformers import RobertaConfig, TFRobertaForSequenceClassification, RobertaTokenizer
from transformers import DistilBertConfig, TFDistilBertForSequenceClassification, DistilBertTokenizer
#from transformers import AlbertConfig, TFAlbertForSequenceClassification, AlbertTokenizer
#from transformers import CamembertConfig, TFCamembertForSequenceClassification, CamembertTokenizer
#from transformers import XLMRobertaConfig, TFXLMRobertaForSequenceClassification, XLMRobertaTokenizer
from transformers import AutoConfig, TFAutoModelForSequenceClassification, AutoTokenizer

TRANSFORMER_MODELS = {
    'bert':       (BertConfig, TFBertForSequenceClassification, BertTokenizer),
    'xlnet':      (XLNetConfig, TFXLNetForSequenceClassification, XLNetTokenizer),
    'xlm':        (XLMConfig, TFXLMForSequenceClassification, XLMTokenizer),
    'roberta':    (RobertaConfig, TFRobertaForSequenceClassification, RobertaTokenizer),
    'distilbert': (DistilBertConfig, TFDistilBertForSequenceClassification, DistilBertTokenizer),
#    'albert':     (AlbertConfig, TFAlbertForSequenceClassification, AlbertTokenizer),
#    'camembert':  (CamembertConfig, TFCamembertForSequenceClassification, CamembertTokenizer),
#    'xlm_roberta':  (XLMRobertaConfig, TFXLMRobertaForSequenceClassification, XLMRobertaTokenizer)
}
```

**Comment by amaiya** [comment]
Please upgrade to v2.5.1 of transformers:   `pip3 install transformers==2.5.1`.  Thanks.

**Comment by dtuggener** [comment]
Thanks, I can confirm that this solves the issue.
