### ISSUE TITLE
entities_from_conll2003 cant decode some characters on windows.

### ISSUE THREAD

**Issue by Niekvdplas** [amaiya/ktrain#92]
Dear Amaiya, 

Again amazing work and thank you very much for expanding on the NER theme. For me, it works perfectly on UNIX based systems(Ubuntu) . On Windows however, a UnicodeDecodeError is thrown: 

(This is thrown on the exact example of the Dutch NER without the %-lines and on a windows machine)

Traceback (most recent call last):                                                                                          File "make_ner_predictor.py", line 14, in <module>                                                                          model = txt.sequence_tagger('bilstm', preproc)                                                                          File "C:\Users\Niek\AppData\Local\Programs\Python\Python37\lib\site-packages\ktrain\text\ner\models.py", line 68, in s  equence_tagger                                                                                                                emb_model, word_embedding_dim = preproc.get_embed_model(verbose=verbose)                                                File "C:\Users\Niek\AppData\Local\Programs\Python\Python37\lib\site-packages\ktrain\text\ner\preprocessor.py", line 64  , in get_embed_model                                                                                                          embs = tpp.load_wv(self.wv_path_or_url, verbose=verbose)                                                                File "C:\Users\Niek\AppData\Local\Programs\Python\Python37\lib\site-packages\ktrain\text\preprocessor.py", line 114, i  n load_wv                                                                                                                     length = file_len(wv_path)                                                                                              File "C:\Users\Niek\AppData\Local\Programs\Python\Python37\lib\site-packages\ktrain\text\preprocessor.py", line 106, i  n file_len                                                                                                                    for i, l in enumerate(f):                                                                                               File "C:\Users\Niek\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode                     return codecs.charmap_decode(input,self.errors,decoding_table)[0]                                                     UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 300: character maps to <undefined>                 

This is because the file is not using the right encoding. A way to go around this should be file = open(filename, encoding=ENCODINGHERE)  I think. I hope you can work with this.

**Comment by amaiya** [comment]
Thanks for reporting the issue.  The `entities_from_conll2003` function along with others like `entities_from_txt` accept an encoding argument that was previously set to `latin1` as default.  This apparently works in Linux but not in Windows.  I have changed the default to None, in which case the encoding is discovered automatically regardless of whether it is UTF-8, UTF-16 (e.g., Arabic), etc.

I haven't tested this on Windows, but it should hopefully work now.  Please try now with v0.11.2 on Windows.

Thanks again.

**Comment by Niekvdplas** [comment]
Still poses the exact same error, I will try to figure out what is causing it and let you know.

**Comment by amaiya** [comment]
Actually, I misread the error.  I think I know the cause, as it came up before on Windows from another user.  Standby and I will post another fix.

**Comment by amaiya** [comment]
I think the problem was with a new function `filelen` with reads the file to determine the number of lines for a progress bar for loading and processing the word vector file.  It was not specifying `encoding='utf-8' when reading the word vector file, which causes problems on Windows.

Fix was included in v0.11.3.  Please try it again on Windows.  Thanks.

**Comment by Niekvdplas** [comment]
It is indeed fixed! Thanks :-)
