### ISSUE TITLE
An error occurs with nothing on the tensorboard.

### ISSUE THREAD

**Issue by gyunggyung** [amaiya/ktrain#97]
An error occurs with nothing on the tensorboard!!!!

```
	tbCallBack = keras.callbacks.TensorBoard(log_dir=logdir, write_graph=True, write_images=True)

	learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)

	learner.fit_onecycle(3e-5, int(epoch),checkpoint_folder = checkpoint_path, callbacks=[tbCallBack])
```

![캡처](https://user-images.githubusercontent.com/26733242/77401847-f77d8b00-6df0-11ea-8508-44095791cb19.JPG)

tensorboard --logdir=./logs/ --host=127.0.0.1tensorboard --logdir==training:logs/ --host=127.0.0.1
2020-03-24 16:59:18.934221: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Exception in thread Reloader:
Traceback (most recent call last):
  File "c:\users\hwnau\.conda\envs\cuda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\hwnau\.conda\envs\cuda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\application.py", line 480, in _reload
    multiplexer.Reload()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 246, in Reload
    Worker()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 224, in Worker
    accumulator.Reload()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 177, in Reload
    for event in self._generator.Load():
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 89, in Load
    for event in self._LoadInternal():
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 109, in _LoadInternal
    self._InitializeLoader()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 168, in _InitializeLoader
    self._SetPath(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 192, in _SetPath
    self._loader = self._loader_factory(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\event_file_loader.py", line 42, in __init__
    self._reader = _pywrap_tensorflow.PyRecordReader_New(
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'PyRecordReader_New'

TensorBoard 1.15.0 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
E0324 16:59:27.287061 15336 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\application.py", line 395, in __call__
    return self.exact_routes[clean_path](environ, start_response)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\wrappers\base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 188, in _serve_runs
    run_names.sort(key=get_first_event_timestamp)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 182, in get_first_event_timestamp
    return self._multiplexer.FirstEventTimestamp(run_name)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 306, in FirstEventTimestamp
    return accumulator.FirstEventTimestamp()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 227, in FirstEventTimestamp
    event = next(self._generator.Load())
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 89, in Load
    for event in self._LoadInternal():
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 109, in _LoadInternal
    self._InitializeLoader()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 168, in _InitializeLoader
    self._SetPath(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 192, in _SetPath
    self._loader = self._loader_factory(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\event_file_loader.py", line 42, in __init__
    self._reader = _pywrap_tensorflow.PyRecordReader_New(
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'PyRecordReader_New'
W0324 16:59:27.369062 16352 core_plugin.py:185] Unable to get first event timestamp for run =training\train: No event timestamp could be found
E0324 16:59:27.406058 16352 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\application.py", line 395, in __call__
    return self.exact_routes[clean_path](environ, start_response)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\werkzeug\wrappers\base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 188, in _serve_runs
    run_names.sort(key=get_first_event_timestamp)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 182, in get_first_event_timestamp
    return self._multiplexer.FirstEventTimestamp(run_name)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 306, in FirstEventTimestamp
    return accumulator.FirstEventTimestamp()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 227, in FirstEventTimestamp
    event = next(self._generator.Load())
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 89, in Load
    for event in self._LoadInternal():
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 109, in _LoadInternal
    self._InitializeLoader()
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 168, in _InitializeLoader
    self._SetPath(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\directory_watcher.py", line 192, in _SetPath
    self._loader = self._loader_factory(path)
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\backend\event_processing\event_file_loader.py", line 42, in __init__
    self._reader = _pywrap_tensorflow.PyRecordReader_New(
  File "c:\users\hwnau\.conda\envs\cuda\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'PyRecordReader_New'
W0324 16:59:27.489111 16352 core_plugin.py:185] Unable to get first event timestamp for run =training\train: No event timestamp could be found
W0324 16:59:27.490113 16352 core_plugin.py:185] Unable to get first event timestamp for run =training\validation: No event timestamp could be found

**Comment by gyunggyung** [comment]
Take a good look

**Comment by amaiya** [comment]
Hello:  I wasn't able to reproduce this issue.  It looks like some sort of TF/TensorBoard issue on our end, as opposed to a *ktrain* issue. Probably a versioning issue.
